const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let boot,rows=[],filters={},view='explore',mode='list',offset=0,requestId=0,calendarMonth='',selectedDay='';
const comparison=new Map();
const fmt=n=>Number(n||0).toLocaleString('ko-KR');
const dateLabel=s=>new Date(s+'T00:00:00Z').toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short',timeZone:'UTC'});
const cabinLabel=r=>r.cabin==='FIRST'?'일등석':'프레스티지';
const params=extra=>new URLSearchParams(Object.entries({...filters,...extra}).filter(([,v])=>v!==''&&v!=null));
async function api(url,method='GET',data){const r=await fetch(url,{method,headers:{'Content-Type':'application/json','x-local-token':boot?.token||''},...(data?{body:JSON.stringify(data)}:{})});const value=await r.json();if(!r.ok)throw Error(value.error||'요청을 처리하지 못했어요.');return value;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4000);}
function months(){const out=[];if(!boot?.report.start_date)return out;let d=new Date(boot.report.start_date.slice(0,7)+'-01T00:00:00Z');while(d.toISOString().slice(0,7)<=boot.report.end_date.slice(0,7)){out.push(d.toISOString().slice(0,7));d.setUTCMonth(d.getUTCMonth()+1);}return out;}
function metadata(){const b=boot,r=b.report;$('#source-time').textContent=`${r.source_updated_at||'미확인'} 기준 · 실시간 자료 아님`;$('#saved-count').textContent=b.favorites;const total=months().length*b.routes.length;$('#stats').innerHTML=[['가능한 항공편·객실',fmt(b.stats.available),'건','잔여 좌석 수가 아닌 조회 결과'],['떠날 수 있는 도시',fmt(b.stats.destinations),'곳',`수집 대상 ${b.routes.length}개 목적지`],['선택 가능한 출발일',fmt(b.stats.dates),'일','프레스티지 · 일등석'],['수집한 노선·월',`${r.coverage.length} <small>/ ${total}</small>`,'',r.complete?'전체 조회 완료':r.attempt_complete?'조회 불가 구간 별도 표시':b.scan.running?'남은 구간을 수집하고 있어요':'부분 수집 · 미조회 구간 있음']].map(([a,n,u,s])=>`<article class="stat"><div class="stat-label">${a}</div><div class="stat-number">${n}<small>${u}</small></div><div class="stat-sub">${s}</div></article>`).join('');$('#coverage-note').textContent=r.complete?'조회가 완료된 공개 대상 노선의 결과입니다.':(r.attempt_complete?`전체 요청 완료 · ${r.unqueryable?.length||0}개 노선·월은 항공사 조회 불가. 좌석 없음이 아닙니다.`:'부분 수집 결과입니다. 아직 조회하지 않은 노선·월은 좌석 없음으로 판단하지 않습니다.');}
function options(){const dest=$('#destination').value,month=$('#month').value;$('#destination').innerHTML='<option value="">모든 목적지</option>'+boot.routes.filter(r=>!filters.region||r.region===filters.region).map(r=>`<option value="${esc(r.code)}">${esc(r.city||r.code)} · ${esc(r.code)}</option>`).join('');$('#destination').value=dest;$('#month').innerHTML='<option value="">전체 기간</option>'+months().map(m=>`<option value="${m}">${m.replace('-','년 ')}월</option>`).join('');$('#month').value=month;}
function rowHtml(r){return `<article class="flight-row"><input class="compare-check" type="checkbox" aria-label="${esc(r.flight+' '+r.date+' '+cabinLabel(r))} 비교 선택" data-compare="${r.id}"><div class="city-cell"><span class="city">${esc(r.city)}</span><span class="subline">ICN → ${esc(r.destination)} · ${esc(r.country)}</span></div><div class="flight-date">${dateLabel(r.date)}<span class="subline">${r.date.slice(0,4)}</span></div><div class="flight-time">${esc(r.time)}<span class="subline">${esc(r.flight)}</span></div><div class="cabin-cell"><span class="cabin ${r.cabin==='FIRST'?'first':''}">${cabinLabel(r)}</span><span class="subline">${r.cabin==='FIRST'?'보너스 / 좌석승급':'마일리지 보너스'}</span></div><button class="detail-button" data-detail="${r.id}">상세 보기</button><button class="favorite ${r.saved?'saved':''}" data-favorite="${r.id}" aria-label="${r.saved?'저장 해제':'항공편 저장'}" aria-pressed="${!!r.saved}">${r.saved?'♥':'♡'}</button></article>`;}
async function refresh(){const id=++requestId;try{
 const data=await api('/api/seats?'+params({offset,limit:30,saved:view==='saved'?'true':'',...(mode==='calendar'?{month:calendarMonth||filters.month||months()[0],date:selectedDay}:{} )}));
 if(id!==requestId)return;
 if(offset>0&&!data.rows.length&&data.total>0){offset=Math.floor((data.total-1)/30)*30;return refresh();}
 rows=data.rows;$('#result-count').textContent=`${fmt(data.total)}건`;
 $('#results').innerHTML=rows.length?`<div class="flight-list"><div class="list-head"><span>비교</span><span>목적지</span><span>출발일</span><span>현지 출발시간</span><span>좌석 등급</span><span></span><span>저장</span></div>${rows.map(rowHtml).join('')}</div>`:`<div class="empty"><strong>${view==='saved'?'저장한 항공편이 없어요':'조건에 맞는 항공편이 없어요'}</strong>${view==='saved'?'항공편 옆 하트를 누르면 여기에 모아 볼 수 있어요.':'검색 조건을 넓히거나 수집 범위를 확인해 주세요.'}<br><button class="text-button" data-clear-filters>검색 조건 초기화</button></div>`;
 $('#results').querySelectorAll('[data-compare]').forEach(el=>el.checked=comparison.has(el.dataset.compare));
 if(view==='saved')for(const row of rows){if(!isCurrent(row)||!row.available){const el=$(`[data-detail="${row.id}"]`).closest('.flight-row');el.classList.add('historical');el.querySelector('.cabin-cell').insertAdjacentHTML('beforeend',`<span class="unverified">${!isCurrent(row)?'현재 범위 미확인':'현재 가능 표시 없음'}</span>`);}}
 $('#pagination').innerHTML=data.total>30?`<button data-page="-1" ${offset===0?'disabled':''}>이전</button><span>${Math.floor(offset/30)+1} / ${Math.ceil(data.total/30)}</span><button data-page="1" ${offset+30>=data.total?'disabled':''}>다음</button>`:'';
 $('#calendar').hidden=mode!=='calendar';if(mode==='calendar')await renderCalendar(id);
 }catch(e){if(id===requestId)$('#results').innerHTML=`<div class="empty"><strong>결과를 불러오지 못했어요</strong>${esc(e.message)}<br><button class="text-button" data-retry>다시 시도</button></div>`;}}
function readFilters(){for(const key of ['destination','month','cabin','start','end'])filters[key]=$('#'+key).value;filters.q=$('#query').value;filters.weekend=$('#weekend').checked?'true':'';filters.sort=$('#sort').value;offset=0;selectedDay='';calendarMonth=filters.month||calendarMonth;refresh();}
$('#regions').onclick=e=>{const b=e.target.closest('[data-region]');if(!b)return;filters.region=b.dataset.region;filters.destination='';$('#destination').value='';$('#regions').querySelectorAll('button').forEach(n=>n.classList.toggle('selected',n===b));options();offset=0;selectedDay='';refresh();};
for(const id of ['destination','month','cabin','start','end','weekend','sort'])$('#'+id).onchange=readFilters;
$('#query').oninput=()=>{clearTimeout(readFilters.timer);readFilters.timer=setTimeout(readFilters,220);};
$('#reset').onclick=()=>{filters={};selectedDay='';calendarMonth=months()[0];for(const id of ['query','destination','month','cabin','start','end'])$('#'+id).value='';$('#weekend').checked=false;$('#sort').value='date';$('#regions button').click();};
$('#export').onclick=()=>{location.href='/api/export?'+params({saved:view==='saved'?'true':'',...(mode==='calendar'?{month:calendarMonth,date:selectedDay}:{})});};
document.onclick=async e=>{try{const p=e.target.closest('[data-page]');if(p){offset+=Number(p.dataset.page)*30;await refresh();}if(e.target.closest('[data-retry]'))await refresh();}catch(err){toast(err.message);}};
function isCurrent(r){return r.source_updated_at===boot.report.source_updated_at&&r.date>=boot.report.start_date&&r.date<=boot.report.end_date&&boot.report.coverage.some(c=>c.destination===r.destination&&c.month===r.date.slice(0,7));}
function syncControls(){options();for(const id of ['destination','month','cabin','start','end'])$('#'+id).value=filters[id]||'';$('#query').value=filters.q||'';$('#weekend').checked=filters.weekend==='true';$('#sort').value=filters.sort||'date';$('#regions').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.region===(filters.region||'')));}
function changeView(next){view=next;offset=0;selectedDay='';$('#explorer').hidden=view==='data';$('#data-view').hidden=view!=='data';$('#page-title').textContent=({explore:'다음 여행, 어디로 갈까요?',saved:'마음에 담아둔 다음 여행',data:'자료가 얼마나 모였을까요?'})[view];$('#results-title').textContent=view==='saved'?'저장한 항공편':'가능한 항공편';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='data')renderData();else refresh();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='saved'){filters={};syncControls();}changeView(b.dataset.view);});
$('#source-detail').onclick=()=>changeView('data');
$('#display-mode').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;mode=b.dataset.mode;offset=0;selectedDay='';calendarMonth=filters.month||calendarMonth||months()[0];$('#display-mode').querySelectorAll('button').forEach(n=>n.classList.toggle('selected',n===b));refresh();};
function openDialog(html,wide=false){const d=$('#dialog');d.classList.toggle('wide',wide);$('#dialog-content').innerHTML=html;if(!d.open)d.showModal();}
$('#dialog .dialog-close').onclick=()=>$('#dialog').close();
$('#dialog').onclick=e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
function flightDetail(r){return `<span class="eyebrow">KOREAN AIR · ${esc(r.flight)}</span><h2 class="detail-heading">서울에서 ${esc(r.city)}까지</h2><div class="ticket-route"><div><strong>ICN</strong><span>서울 / 인천</span></div><span class="route-rule">편도 →</span><div><strong>${esc(r.destination)}</strong><span>${esc(r.city)}</span></div></div><dl class="detail-grid"><div><dt>출발일</dt><dd>${r.date}<br>${dateLabel(r.date)}</dd></div><div><dt>출발 시각 · 현지</dt><dd>${esc(r.time)||'미제공'}</dd></div><div><dt>좌석 등급</dt><dd>${cabinLabel(r)}</dd></div><div><dt>예약 클래스</dt><dd>${esc(r.fare_class)} · ${r.cabin==='FIRST'?'보너스/좌석승급':'보너스'}</dd></div></dl><div class="detail-note">${isCurrent(r)?(r.available?'공개 일일 자료에서 가능으로 표시된 항공편입니다.':'마지막 조회에서 가능 표시가 없습니다.'):'현재 수집 범위에서 확인되지 않은 저장 항공편입니다.'} 잔여 좌석 수·다인원 예약 가능 여부는 제공되지 않습니다.</div><dl class="timestamps"><div><dt>원자료 기준</dt><dd>${esc(r.source_updated_at)} (한국)</dd></div><div><dt>수집 시각</dt><dd>${new Date(r.checked_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} (한국)</dd></div></dl>`;}
async function detail(id){const r=await api('/api/seats/'+id);openDialog(flightDetail(r)+`<div class="dialog-actions"><button class="secondary" data-copy="${r.id}">일정 복사</button><a class="primary" href="https://www.koreanair.com/booking/book-and-manage/award-seat-availability" target="_blank" rel="noreferrer">대한항공에서 확인 ↗</a></div>`);}
async function toggleFavorite(id){const r=await api('/api/seats/'+id);await api('/api/favorite','POST',{id,saved:!r.saved});await updateBootstrap();await refresh();toast(r.saved?'저장을 해제했어요.':'항공편을 저장했어요.');}
function compareBar(){const n=comparison.size;$('#compare-bar').hidden=!n;$('#compare-bar').innerHTML=`<span><b>${n}개</b> 항공편 선택 <small>최대 3개</small></span><button class="text-button" data-clear-compare>선택 해제</button><button class="primary" data-open-compare ${n<2?'disabled':''}>나란히 비교하기</button>`;}
function renderSearches(){const html=boot.searches.length?boot.searches.map(s=>`<div class="saved-search"><button data-search="${s.id}" title="${esc(s.name)}">⌕ <span>${esc(s.name)}</span></button><button data-delete-search="${s.id}" aria-label="${esc(s.name)} 검색 삭제">×</button></div>`).join(''):'<p class="muted small">자주 찾는 조건을 저장해 보세요.</p>';$('#searches').innerHTML=html;}
$('#save-search').onclick=()=>openDialog(`<span class="eyebrow">SAVED SEARCH</span><h2 class="detail-heading">다음에도 빠르게 찾아보세요</h2><p class="muted">현재 지역·날짜·좌석 조건을 이 PC에 저장합니다.</p><form id="search-form"><label>검색 이름<input name="name" maxlength="80" required placeholder="예: 내년 봄 유럽 비즈니스" autofocus></label><div class="dialog-actions"><button class="primary" type="submit">검색 저장</button></div></form><div class="mobile-searches">${$('#searches').innerHTML}</div>`);
document.addEventListener('submit',async e=>{if(e.target.id!=='search-form')return;e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/searches','POST',{name:new FormData(e.target).get('name'),filters});await updateBootstrap();$('#dialog').close();toast('검색 조건을 저장했어요.');}catch(err){toast(err.message);button.disabled=false;}});
async function renderCalendar(id){const month=calendarMonth||filters.month||months()[0];if(!month)return;calendarMonth=month;const data=await api('/api/calendar?'+params({month,date:'',saved:view==='saved'?'true':''}));if(id!==requestId)return;const map=new Map(data.map(r=>[r.date,r])),[year,m]=month.split('-').map(Number),start=new Date(Date.UTC(year,m-1,1)).getUTCDay(),days=new Date(Date.UTC(year,m,0)).getUTCDate();const routes=boot.routes.filter(r=>(!filters.region||r.region===filters.region)&&(!filters.destination||r.code===filters.destination));const done=routes.filter(r=>boot.report.coverage.some(c=>c.destination===r.code&&c.month===month)).length;const unknown=routes.filter(r=>(boot.report.unqueryable||[]).some(c=>c.destination===r.code&&c.month===month)).length;const pending=Math.max(0,routes.length-done-unknown);const noResult=unknown===routes.length&&unknown>0?'조회 불가':pending>0?'미조회 포함':unknown>0?'일부 미확인':'·';let cells=Array(start).fill('<div class="calendar-blank"></div>');for(let n=1;n<=days;n++){const date=`${month}-${String(n).padStart(2,'0')}`,r=map.get(date),outside=date<boot.report.start_date||date>boot.report.end_date;cells.push(`<button class="calendar-day ${r?'has-flights':''} ${selectedDay===date?'chosen':''}" data-day="${date}" ${outside?'disabled':''} aria-label="${date} ${outside?'조회 범위 밖':r?`${r.count}건`:(noResult==='·'?'조건에 맞는 확인 결과 없음':noResult)}"><span>${n}</span><b>${outside?'—':r?fmt(r.count)+'건':noResult}</b>${r?`<small>${r.destinations}개 도시</small>`:''}</button>`);}$('#calendar').innerHTML=`<section class="calendar-card"><div class="calendar-top"><button class="icon-button" data-month-step="-1" aria-label="이전 달" ${month===months()[0]?'disabled':''}>‹</button><h2>${year}년 ${m}월</h2><button class="icon-button" data-month-step="1" aria-label="다음 달" ${month===months().at(-1)?'disabled':''}>›</button><button class="text-button" data-day="">${selectedDay?'선택한 날짜 해제':'월 전체 보기'}</button></div><div class="calendar-grid">${['일','월','화','수','목','금','토'].map(d=>`<div class="weekday">${d}</div>`).join('')}${cells.join('')}</div><p class="calendar-legend">${done}/${routes.length}개 노선 정상 조회${unknown?' · '+unknown+'개 항공사 조회 불가':''}${pending?' · '+pending+'개 미조회':''} · 숫자는 항공편·객실 건수 · 점(·)은 선택 조건에 맞는 결과 없음${selectedDay?' · 선택일 '+selectedDay:''}</p></section>`;}
function renderData(){const r=boot.report,ms=months(),total=ms.length*boot.routes.length,done=r.coverage.length;$('#data-view').innerHTML=`<section class="data-card"><div class="data-top"><div><span class="eyebrow">COLLECTION COVERAGE</span><h2>조회한 범위를 투명하게</h2></div><button class="primary" id="scan" ${boot.scan.running?'disabled':''}>${boot.scan.running?'수집 중…':'공개 자료 다시 수집'}</button></div><p class="muted">${r.start_date} ~ ${r.end_date} · 인천 출발 ${boot.routes.length}개 노선</p><progress value="${done}" max="${total||1}"></progress><div class="progress-caption"><b>${done} / ${total} 노선·월</b><span>${r.complete?'수집 완료':r.attempt_complete?'전체 요청 완료 · 일부 조회 불가':r.failure?'수집 중 오류 발생':boot.scan.running?'수집 진행 중':'부분 수집 · 이어서 조회 가능'}</span></div>${r.failure?`<div class="detail-note">${esc(r.failure)}</div>`:''}<div class="coverage-scroll"><table class="coverage-table"><thead><tr><th>목적지</th>${ms.map(m=>`<th>${m.slice(2,4)}.${m.slice(5)}</th>`).join('')}</tr></thead><tbody>${boot.routes.map(route=>`<tr><th>${esc(route.city||route.code)} <small>${route.code}</small></th>${ms.map(m=>{const c=r.coverage.find(c=>c.destination===route.code&&c.month===m),u=(r.unqueryable||[]).find(c=>c.destination===route.code&&c.month===m);return `<td><span class="coverage-cell ${c?'done':u?'unqueryable':''}" title="${esc(route.code+' '+m+' '+(c?'조회 완료':u?'항공사 조회 불가':'미조회'))}" aria-label="${c?'조회 완료':u?'항공사 조회 불가':'미조회'}">${c?'✓':u?'!':'—'}</span></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p class="small muted">✓ 조회 완료 · ! 항공사가 해당 여정 조회 불가로 응답 · — 미조회. 완료 표시는 좌석이 있다는 뜻이 아닙니다. ATH·BCN·ZAG는 공개 선택지에서 확인되지 않아 대상에 포함하지 않았습니다.</p></section><section class="data-card"><h2>자료와 실시간 조회에 대해</h2><dl class="timestamps"><div><dt>항공사 원자료 시각</dt><dd>${esc(r.source_updated_at)} (한국)</dd></div><div><dt>수집 시작</dt><dd>${r.started_at?new Date(r.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'미확인'}</dd></div><div><dt>완료 시각</dt><dd>${r.finished_at?new Date(r.finished_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 완료되지 않음'}</dd></div></dl><p class="muted">이 사이트는 대한항공의 공개 일일 자료를 사용합니다. 다시 수집해도 항공사 원자료가 갱신되지 않았다면 결과는 같을 수 있습니다. 로그인 없는 실제 실시간 예약 재고 조회는 아직 검증되지 않았습니다.</p><a class="text-button" href="https://www.koreanair.com/booking/book-and-manage/award-seat-availability" target="_blank" rel="noreferrer">공식 자료 확인 ↗</a></section><section class="data-card"><h2>최근 확인한 변화</h2>${boot.changes.length?`<div class="change-list">${boot.changes.map(c=>`<div><b>${esc(c.city)}</b><span>${c.date} · ${cabinLabel(c)}</span><span>${c.kind==='OPENED'?'가능 표시 생김':'가능 표시 사라짐'}</span></div>`).join('')}</div>`:'<p class="muted">아직 비교 가능한 변화 기록이 없습니다. 최초 수집 결과를 신규 좌석으로 표시하지 않습니다.</p>'}</section>`;}
document.addEventListener('click',async e=>{try{
 const el=e.target.closest('button');if(!el)return;
 if(el.dataset.favorite)await toggleFavorite(el.dataset.favorite);
 if(el.dataset.detail)await detail(el.dataset.detail);
 if(el.hasAttribute('data-clear-filters'))$('#reset').click();
 if(el.hasAttribute('data-clear-compare')){comparison.clear();compareBar();await refresh();}
 if(el.hasAttribute('data-open-compare')){const live=await Promise.all([...comparison.keys()].map(id=>api('/api/seats/'+id)));openDialog(`<span class="eyebrow">COMPARE FLIGHTS</span><h2 class="detail-heading">내 여행에 맞는 항공편은?</h2><div class="compare-grid">${live.map(r=>`<article>${flightDetail(r)}</article>`).join('')}</div>`,true);}
 if(el.dataset.copy){const r=await api('/api/seats/'+el.dataset.copy);await navigator.clipboard.writeText(`${r.date} ${r.time} ICN → ${r.destination} ${r.flight} ${cabinLabel(r)}\n대한항공 공개 일일 자료 기준: ${r.source_updated_at}\n예약 가능 여부는 항공사 확인 필요`);toast('일정을 복사했어요.');}
 if(el.dataset.search){const s=boot.searches.find(s=>s.id===Number(el.dataset.search));filters={...s.filters};selectedDay='';calendarMonth=filters.month||months()[0];syncControls();$('#dialog').close();changeView('explore');toast('저장한 검색 조건을 적용했어요.');}
 if(el.dataset.deleteSearch){await api('/api/searches/'+el.dataset.deleteSearch,'DELETE');await updateBootstrap();el.closest('.saved-search')?.remove();toast('검색 조건을 삭제했어요.');}
 if(el.hasAttribute('data-day')){selectedDay=el.dataset.day;offset=0;await refresh();}
 if(el.dataset.monthStep){const ms=months(),next=ms[ms.indexOf(calendarMonth)+Number(el.dataset.monthStep)];if(next){calendarMonth=next;selectedDay='';offset=0;filters.month=next;$('#month').value=next;await refresh();}}
 if(el.id==='scan'){el.disabled=true;try{await api('/api/scan','POST',{});toast('공개 자료 수집을 시작했어요. Edge 창에서 조회합니다.');await updateBootstrap();}catch(err){el.disabled=false;throw err;}}
 }catch(err){toast(err.message);}});
document.addEventListener('change',e=>{const id=e.target.dataset.compare;if(!id)return;if(e.target.checked){if(comparison.size>=3){e.target.checked=false;toast('최대 3개 항공편을 비교할 수 있어요.');return;}comparison.set(id,rows.find(r=>r.id===id));}else comparison.delete(id);compareBar();});
async function updateBootstrap(){boot=await api('/api/bootstrap');metadata();renderSearches();if(view==='data'&&!document.activeElement?.closest('#automation-form'))renderData();}
async function init(){try{await updateBootstrap();options();await refresh();}catch(e){$('#results').innerHTML=`<div class="empty">${esc(e.message)} · 로컬 서버 실행 상태를 확인해 주세요.</div>`;}}
let polling=false;setInterval(async()=>{if(polling||document.hidden||$('#dialog').open)return;polling=true;try{const old=JSON.stringify([boot?.report.coverage.length,boot?.report.source_updated_at,boot?.report.complete,boot?.report.unqueryable?.length,boot?.report.attempt_complete]);await updateBootstrap();if(old!==JSON.stringify([boot.report.coverage.length,boot.report.source_updated_at,boot.report.complete,boot.report.unqueryable?.length,boot.report.attempt_complete])&&view!=='data'&&!$('#results').contains(document.activeElement))await refresh();}catch{toast('서버 연결이 끊겼어요. 저장된 결과는 유지됩니다.');}finally{polling=false;}},8000);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'search_award_flights',description:'Filter the visible Korean Air daily award results. This is not realtime inventory.',inputSchema:{type:'object',properties:{destination:{type:'string'},month:{type:'string'},cabin:{type:'string',enum:['PRESTIGE','FIRST']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['destination','month','cabin'].includes(k)))throw Error('Invalid filters');if(input.destination&&!boot.routes.some(r=>r.code===input.destination))throw Error('Unknown destination');if(input.month&&!months().includes(input.month))throw Error('Month outside coverage');if(input.cabin&&!['PRESTIGE','FIRST'].includes(input.cabin))throw Error('Invalid cabin');filters={...input};mode='list';$('#display-mode').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));syncControls();view='explore';changeView(view);await refresh();return {source_type:'daily',source_updated_at:boot.report.source_updated_at,results:rows};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
const renderDataBase=renderData;
renderData=()=>{
 renderDataBase();
 if(boot.scan.paused){const scan=$('#scan');scan.disabled=true;scan.textContent='수집 일시 중지';}
 const job=boot.scan,statusName={running:'실행 중',stopping:'중단 중',stopped:'중단됨',completed:'완료',failed:'오류'};
 $('#data-view').insertAdjacentHTML('afterbegin',`<section class="data-card"><div class="data-top"><div><span class="eyebrow">LOCAL AUTOMATION</span><h2>수집은 프로그램에 맡기세요</h2></div>${job.can_stop?'<button class="secondary" id="stop-scan">현재 수집 중단</button>':''}</div><p class="muted">이 PC와 로컬 서버가 켜져 있을 때 설정한 시각에 하루 한 번 실행합니다. 브라우저 조회가 필요하므로 Windows 사용자 세션도 유지해 주세요.</p><form id="automation-form"><div class="automation-controls"><label class="check"><input name="enabled" type="checkbox" ${job.enabled?'checked':''}>매일 자동 수집</label><label>한국 시간<input name="time" type="time" required value="${esc(job.time||'09:10')}"></label><button class="primary" type="submit">설정 저장</button></div></form><p class="small muted">다음 실행: ${job.enabled&&job.next_run?new Date(job.next_run).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' (한국)':'자동 수집 꺼짐'} · 오류나 차단은 기록하고 멈춥니다. 로그인 자동화는 하지 않습니다.</p><details><summary>최근 실행 이력</summary>${(job.history||[]).length?`<div class="change-list">${job.history.map(h=>`<div><span>${new Date(h.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</span><span>${h.trigger==='daily'?'예약 실행':'수동 실행'}</span><b>${statusName[h.status]||esc(h.status)}</b></div>`).join('')}</div>`:'<p class="small muted">프로그램이 관리한 실행 이력이 아직 없습니다.</p>'}</details></section>`);
 if(job.paused){$('#automation-form').querySelectorAll('input,button').forEach(el=>el.disabled=true);$('#automation-form').insertAdjacentHTML('beforebegin','<p class="detail-note">수집 일시 중지 · 저장된 자료만 표시합니다. 현재 실행에서는 수동·자동 수집을 모두 차단했습니다.</p>');}
};
document.addEventListener('submit',async e=>{
 if(e.target.id!=='automation-form')return;e.preventDefault();
 const f=new FormData(e.target),button=e.target.querySelector('button');button.disabled=true;
 try{await api('/api/automation','POST',{enabled:f.has('enabled'),time:f.get('time')});button.blur();await updateBootstrap();renderData();toast('자동 수집 설정을 저장했어요.');}catch(err){button.disabled=false;toast(err.message);}
});
document.addEventListener('click',async e=>{const b=e.target.closest('#stop-scan');if(!b)return;b.disabled=true;try{await api('/api/scan/stop','POST',{});await updateBootstrap();toast('수집 중단을 요청했어요. 저장된 결과는 유지됩니다.');}catch(err){b.disabled=false;toast(err.message);}});
init();
